spring:
  datasource:
    url: jdbc:mysql://localhost:3306/land?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&connectTimeout=0&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    username: root
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: update
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  #security
  #security:
   # user:
    #  name: shulu
     # password: shulu